tmux new -d -s dev;
tmux new -d -s watch-backend;
tmux new -d -s run-backend;
tmux new -d -s run-frontend;
tmux send-keys -t dev "cd ${PWD}" Enter;
tmux send-keys -t watch-backend "cd ${PWD}" Enter;
tmux send-keys -t watch-backend "npm run watch-backend" Enter;
tmux send-keys -t run-backend "cd ${PWD}" Enter;
tmux send-keys -t run-backend "source .env" Enter;
tmux send-keys -t run-backend "npm run run-backend" Enter;
tmux a -t run-backend;
